name = Bonus
description = Custom layout for Bonus page.
preview = preview.png
template = bonus-layout

; Regions
regions[branding]       	= Branding
regions[navigation]     	= Navigation bar
regions[sidebar_header] 	= Sidebar header
regions[sidebar_links] 		= Sidebar links
regions[admin_blocks]  		= Admin blocks
regions[header]         	= Header
regions[highlighted]    	= Highlighted
regions[help]           	= Help
regions[content]        	= Content
regions[sidebar_first]  	= First sidebar
regions[footer]         	= Footer

; Stylesheets
stylesheets[all][] = css/vedic.styles.css
stylesheets[all][] = css/layouts/bonus/bonus.layout.css
stylesheets[all][] = css/layouts/bonus/bonus.layout.no-query.css

; Javascripts
scripts[] = js/layouts/bonus/main.js
