name = Basic Page
description = Basic page layout.
preview = preview.png
template = page-layout

; Regions
regions[branding]       	= Branding
regions[navigation]     	= Navigation bar
regions[sidebar_header] 	= Sidebar header
regions[sidebar_links] 		= Sidebar links
regions[admin_blocks]  		= Admin blocks
regions[header]         	= Header
regions[content_header]    	= Content Header
regions[content]        	= Content
regions[sidebar_first]  	= First sidebar
regions[footer]         	= Footer

; Stylesheets
stylesheets[all][] = semantic/dist/semantic.css
stylesheets[all][] = js/lib/bxslider/jquery.bxslider.css
stylesheets[all][] = css/vedic.styles.css
stylesheets[all][] = css/layouts/course-info/course-info.layout.css
stylesheets[all][] = css/layouts/course-info/course-info.layout.no-query.css

; Javascripts
scripts[] = js/lib/bxslider/jquery.bxslider.js
scripts[] = js/layouts/course-info/main.js
